### PR TITLE
create `do_great_circle`, `do_create_xgrid_order1`, and `do_create_xgrid_order2` 

### PR DESCRIPTION
**Pull request by mlee03**
In this PR, `do_great_clrcle`, `do_create_xgrid_order1`, and `do_create_xgrid_order2` functions have been created and is called in _setup_conserve_interp_.  Creation of these function cleans up the non-read portion of _setup_conserve_interp_ and will make the process of adding OpenACC directives easier.  Future plans to combine `do_create_xgrid_order1` and `do_create_xgrid_order2` will be considered.

Remapping  of scalar data from cubed-sphere to latlon grid with conserve_interp1 and conserve_interp2 methods have been tested on CPUs.

### CODE REVIEW

**Comment by mlee03** [comment]
This PR is not ready.  CI passes and the code compiles when generating the parallelized versions of fregrid, etc.  But the code does not compile with nvc for a very good reason:  an argument was not passed into a function.  It's strange that nvc is the only compiler that caught this mistake?

**Comment by mlee03** [comment]
PR is ready

**Comment by mlee03** [comment]
@ngs333 ready for your review.  Let me know if you want to meet up to discuss this PR for clarifications/problems, etc :)

**Comment by ngs333** [comment]
> @ngs333 ready for your review. Let me know if you want to meet up to discuss this PR for clarifications/problems, etc :)

OK Thanks this (and not #256) will be the next one I review.

**Review by ngs333 — APPROVED** [review]

**Pull request merged**
