### PR TITLE
Completing the do_cube_transform implementation in make_hgrid v2.0

### PR DESCRIPTION
**Pull request by ngs333**
This PR completes the do_cube transform implementation in make_hgrid. The feature was requested in issue https://github.com/NOAA-GFDL/FRE-NCtools/issues/179. Upon code inspection, exploration and testing we determined that only minor code changes were needed to complete its implementation. 

This is an important feature which was unfinished and therefore without testing, exercise or coverage in any unit test, and so a reference unit test (# 33) was added.  The unit tests compare make_hgrid horiz grids created analyticall vs created from reference FV3 output grid spec files. Additional manual testing was done and further discussion is available in issue https://github.com/NOAA-GFDL/FRE-NCtools/issues/179.

The earlier version of this PR (https://github.com/NOAA-GFDL/FRE-NCtools/pull/194) was closed without merging in order to facilitate complete remove the larger (  approx C128 size) reference files from github.

### CODE REVIEW

**Comment by ngs333** [comment]
The PR was closed to facilitate the complete removal of the very large unit test reference files. There is a replacement PR that uses smaller (C48 size) files https://github.com/NOAA-GFDL/FRE-NCtools/pull/195 which are more convenient.

**Comment by ngs333** [comment]
Accidentally closed wrong PR. Re-opening.

**Review by bensonr — COMMENTED** [review]
@underwoo - do we want any datafiles in our test suite?  If not, is there another way to make them available for CI testing within the container?

**Review by lharris4 — APPROVED** [review]
Looks good to me. Thanks.

**Comment by ngs333** [comment]
> > @underwoo - do we want any datafiles in our test suite? If not, is there another way to make them available for CI testing within the container?
> 
> @underwoo , @bensonr The Test33 reference dataset is six files of 132 KB each. Current size of the t directory immediately after a git clone is 887 MB.

@bensonr @underwoo @ceblanton 
Concerning datafiles in our test suite, this perhaps should be theme that is part of the next release (after 2022.02), and I added I added existing issues ( https://github.com/NOAA-GFDL/FRE-NCtools/issues/76 , https://github.com/NOAA-GFDL/FRE-NCtools/issues/51) to the next project.

**Pull request merged**
