### PR TITLE
Remove the use of average_* variables and use time_bnds variables instead

### LINKED ISSUE #273: timeaveraging tool should use standard time variables only
**Is your feature request related to a problem? Please describe.**
FMS history output has traditionally included time bounds metadata in a non-standard convention. i.e.
* 3 time bounds variables: average_T1, average_T2, and average_DT
  * average_T1 is the start time for the averaging period (in the same time units as `time`)
  * average_T2 is the end time for the averaging period
  * average_DT is the length of the averaging period, in days
```
	double average_T1(time) ;
		average_T1:_FillValue = 1.e+20 ;
		average_T1:missing_value = 1.e+20 ;
		average_T1:units = "days since 1979-01-01 00:00:00" ;
		average_T1:long_name = "Start time for average period" ;
	double average_T2(time) ;
		average_T2:_FillValue = 1.e+20 ;
		average_T2:missing_value = 1.e+20 ;
		average_T2:units = "days since 1979-01-01 00:00:00" ;
		average_T2:long_name = "End time for average period" ;
	double average_DT(time) ;
		average_DT:_FillValue = 1.e+20 ;
		average_DT:missing_value = 1.e+20 ;
		average_DT:units = "days" ;
		average_DT:long_name = "Length of average period" ;
```
* These 3 variables are referenced as a variable attribute in each diagnostic. e.g.
```
		dis_liq:time_avg_info = "average_T1,average_T2,average_DT" ;
```

The problem is that there is also a standard way to specify the same time bounds information, specified in the CF standards.

* One `time_bounds` variable, with an extra `nv` dimension, that species both `average_T1` and `average_T2`.
```
	double nv(nv) ;
		nv:long_name = "vertex number" ;
	double time_bnds(time, nv) ;
		time_bnds:units = "days since 1979-01-01 00:00:00" ;
		time_bnds:long_name = "time axis boundaries" ;
```
* This `time_bounds` variable is refernced as a variable attribute of `time`:
```
		time:bounds = "time_bnds" ;
```

**Describe the solution you'd like**
1. The timeaveraging tool should read and use the CF standard `time:bounds` attribute to find the time bounds variable (and not use the nonstandard average_(T1|T2|DT) variables.
2. The timeaveraging tool should write output time bounds in the standard convention (and not write the nonstandard variables)

**Describe alternatives you've considered**
Continuing to output duplicate time bounds information is a bad idea, and the diag manager rewrite is a good opportunity to remove unneeded legacy conventions.

**Additional context**
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#cell-boundaries

### LINKED ISSUE #274: fregrid should use standard time variables only
**Is your feature request related to a problem? Please describe.**
FMS history output has traditionally included time bounds metadata in a non-standard convention. i.e.
* 3 time bounds variables: average_T1, average_T2, and average_DT
  * average_T1 is the start time for the averaging period (in the same time units as `time`)
  * average_T2 is the end time for the averaging period
  * average_DT is the length of the averaging period, in days
```
	double average_T1(time) ;
		average_T1:_FillValue = 1.e+20 ;
		average_T1:missing_value = 1.e+20 ;
		average_T1:units = "days since 1979-01-01 00:00:00" ;
		average_T1:long_name = "Start time for average period" ;
	double average_T2(time) ;
		average_T2:_FillValue = 1.e+20 ;
		average_T2:missing_value = 1.e+20 ;
		average_T2:units = "days since 1979-01-01 00:00:00" ;
		average_T2:long_name = "End time for average period" ;
	double average_DT(time) ;
		average_DT:_FillValue = 1.e+20 ;
		average_DT:missing_value = 1.e+20 ;
		average_DT:units = "days" ;
		average_DT:long_name = "Length of average period" ;
```
* These 3 variables are referenced as a variable attribute in each diagnostic. e.g.
```
		dis_liq:time_avg_info = "average_T1,average_T2,average_DT" ;
```

The problem is that there is also a standard way to specify the same time bounds information, specified in the CF standards.

* One `time_bounds` variable, with an extra `nv` dimension, that species both `average_T1` and `average_T2`.
```
	double nv(nv) ;
		nv:long_name = "vertex number" ;
	double time_bnds(time, nv) ;
		time_bnds:units = "days since 1979-01-01 00:00:00" ;
		time_bnds:long_name = "time axis boundaries" ;
```
* This `time_bounds` variable is refernced as a variable attribute of `time`:
```
		time:bounds = "time_bnds" ;
```

**Describe the solution you'd like**
1. fregrid should read and use the CF standard `time:bounds` attribute to find the time bounds variable (and not use the nonstandard average_(T1|T2|DT) variables.
2. fregrid should write output time bounds in the standard convention (and not write the nonstandard variables)

**Describe alternatives you've considered**
Continuing to output duplicate time bounds information is a bad idea, and the diag manager rewrite is a good opportunity to remove unneeded legacy conventions.

**Additional context**
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#cell-boundaries

### PR DESCRIPTION
**Pull request by uramirez8707**
Fixes #273
Fixes #274

I tried this using output from the old diag manager (which includes the average_* variables) and this updated reproduces the master branch.

I tried this using output from the new diag manager (which does not have the average_* variables). This update reproduces the output from the old diag manager.

### CODE REVIEW

**Comment by uramirez8707** [comment]
FYI @ceblanton

**Comment by ilaflott** [comment]
tested on GFDL work-station, using a NetCDF file from [fre-python-tool's time-averager](https://github.com/NOAA-GFDL/fre-python-tools/blob/fef0b784b5f5c1c276052bbcc2d996426bb18ace/tests/time_avg_test_files/atmos.197901-198312.LWP.nc).

exact function call to create averaged file: `./postprocessing/timavg/timavg.csh -r8 -mb -o FOO atmos.197901-198312.LWP.nc`

compared against output of [old `timavg.csh` output genereated for fre-python-tools tests](https://github.com/NOAA-GFDL/fre-python-tools/blob/fef0b784b5f5c1c276052bbcc2d996426bb18ace/examples/run_timavgs_CLI_examples.sh#L32).

stored the header info from `ncdump -h` into text files, then `diff`, yields
```bash-4.4$ diff FOO_header_text TEST_header_text 
1c1
< netcdf FOO {
---
> netcdf fre_nctools_timavg_CLI_test_r8_mb_atmos_LWP_1979_5y {
16a17
> 		LWP:time_avg_info = "average_T1,average_T2,average_DT" ;
46a48,56
> 	double average_T1(time) ;
> 		average_T1:long_name = "Start time for average period" ;
> 		average_T1:units = "days since 1979-01-01 00:00:00" ;
> 	double average_T2(time) ;
> 		average_T2:long_name = "End time for average period" ;
> 		average_T2:units = "days since 1979-01-01 00:00:00" ;
> 	double average_DT(time) ;
> 		average_DT:long_name = "Length of average period" ;
> 		average_DT:units = "days" ;
```
this is the difference in metadata desired and described in [issue 273](https://github.com/NOAA-GFDL/FRE-NCtools/issues/273) and [issue 274](https://github.com/NOAA-GFDL/FRE-NCtools/issues/274). so, YAY!

numerical results bitwise identical as well, can be seen by `ncdiff` calls between the two files.

**Review by ilaflott — APPROVED** [review]
all looks good to me

**Comment by ceblanton** [comment]
Let's confirm that timavg.csh chokes as we think it does and should if the time_bounds are missing.

if timavg.csh hard fails when run on old/uncompliant history files (that don't have time_bounds) no one will end up with incorrect output, at least.

**Comment by uramirez8707** [comment]
> Let's confirm that timavg.csh chokes as we think it does and should if the time_bounds are missing.
> 
> if timavg.csh hard fails when run on old/uncompliant history files (that don't have time_bounds) no one will end up with incorrect output, at least.

This is what I get when I use a file that does not have the time_bounds:
```
 NETCDF ERROR in program time_average
 error getting varid for time bounds
 NetCDF: Variable not found

Program aborted. Backtrace:
#0  0x402c39 in ???
#1  0x403a63 in ???
#2  0x40b554 in ???
#3  0x40240c in ???
#4  0x2b70608e5554 in ???
#5  0x40243c in ???
#6  0xffffffffffffffff in ???
Abort
```

**Comment by ceblanton** [comment]
Thanks for checking that. I'll merge and deploy into fre-nctools/test at GFDL now.

**Review by ceblanton — APPROVED** [review]

**Pull request merged**
