### PR TITLE
remove deprecated `reproduce_siena` option 

### PR DESCRIPTION
**Pull request by rem1776**
just removes the old option

### CODE REVIEW

**Review by mlee03 — APPROVED** [review]

**Comment by mlee03** [comment]
@rem1776, could you make a quick issue that goes along with this PR?

**Comment by rem1776** [comment]
We actually had an issue for this already, but it was marked as closed: #232.

No explanation as to why its closed tho, maybe it was still being used by someone?

**Review by ceblanton — APPROVED** [review]
nice!

**Comment by rem1776** [comment]
> We actually had an issue for this already, but it was marked as closed: #232.
> 
> 
> 
> No explanation as to why its closed tho, maybe it was still being used by someone?

Double checked with Niki and he said it should be fine to remove. I guess why that original issue was closed will remain a mystery, but this PR should be good to go in.

**Comment by mlee03** [comment]
Thanks Ryan!

**Pull request merged**
