### PR TITLE
Turn off ocean-model-grid-generator subtool for GFDL PPAN site

### PR DESCRIPTION
**Pull request by ceblanton**
PP/AN does not have open Internet access needed for virtual envcreating and testing.

Related to GFDL site file adjustments for 2022.01 (#99 )

### CODE REVIEW

**Comment by underwoo** [comment]
I have one question.  Why?  #99 does not explain why OMGG needs to be off for PPAN.

**Review by underwoo — COMMENTED** [review]
Please let me know why OMGG needs to be off for PPAN nodes.

**Comment by ngs333** [comment]
> Please let me know why OMGG needs to be off for PPAN nodes.

@underwoo 
@ceblanton attributed errors in setting up the venv to firewall settings for PPAN. He may be able to give
additional info when he returns.

**Comment by underwoo** [comment]
@ngs333, thank you for the information.  Depending on what is blocked, we should be able to put in a CM request to open firewall ports.  I would rather go down that path than remove something the users will expect to be available on that platform.

**Comment by ceblanton** [comment]
@underwoo, @ngs333 is correct. The PP/AN firewall ports are blocking some part of the python environment testing and creation. I agree opening the ports would be better.

**Comment by chanwilson** [comment]
I don't see the details on what python module is attempting to be installed?

**Comment by ceblanton** [comment]
These pip calls fail from the ocean-model-grid-generator package, when testing or installing the python virtual environment:

```
python3 -m pip install --upgrade pip
python3 -m pip install pytest
```

Yes, I believe access to the PyPI index (https://pypi.org/) will resolve this.

**Comment by ceblanton** [comment]
Running the pip commands with verbose logging shows that they are trying to access two locations:

```
https://pypi.org
https://files.pythonhosted.org
```

@chanwilson and @underwoo, I believe I should request those two locations for port 443, then. Should I request port 80 as well?

**Comment by underwoo** [comment]
@ceblanton, @chanwilson will know better, but to be safe please request both ports 80 and 443.  A quick google search didn't return anything specific about PyPi for firewall rules.

**Comment by ceblanton** [comment]
Help desk ticket submitted. Let's close this, then.

**Pull request closed without merging**
