### PR TITLE
Completing the do_cube_transform implementation in make_hgrid

### PR DESCRIPTION
**Pull request by ngs333**
This PR completes the do_cube transform implementation in make_hgrid. The feature was requested in issue
https://github.com/NOAA-GFDL/FRE-NCtools/issues/179. Upon code inspection only minor code changes were needed to
complete its implementation.  This is an important feature which was unfinished and therefore without testing, exercise or coverage in any unit test, and so a reference unit test (# 33) was added. Testing done is considerable and further discussion is available in issue #179.

### CODE REVIEW

**Comment by lharris4** [comment]
Hi, Miguel. Thanks for putting this together. What precisely does this code do? I don't see any code specific to how the do_cube_transform is done; all I see is another code branch that computes the area, and nothing about how to do the transform itself.

Lucas

**Comment by ngs333** [comment]
@lharris4 
Hi Lucas, the PR is only showing code changes. The use of the routine cube_transform() is whats changed, and not the routine itself.  The routine cube_transform() is in file create_gnomonic_cubit_grid.c in dir tools/make_hgrid; lines 1398ff.

**Comment by lharris4** [comment]
Hi, Miguel. Thanks. I think this looks good, then.

**Review by lharris4 — APPROVED** [review]

**Comment by ngs333** [comment]
The PR was closed to facilitate the complete removal of the very large unit test reference files. There is a replacement PR that uses smaller (C48 size) files https://github.com/NOAA-GFDL/FRE-NCtools/pull/195 which are more convenient.

**Pull request closed without merging**
