### PR TITLE
Bring in last updates from GFDL's gitlab

### LINKED ISSUE #13: Bring in last updates from GFDL's gitlab
GFDL's gitlab had been pushing new updates, which stopped working in mid-June due to new large committed files triggering github's pre-commit hook which refuses files larger than 100 MB.

Missing updates from GFDL's gitlab (https://gitlab.gfdl.noaa.gov/fre/fre-nctools) need to be added here.

Any large files can be symlinked to GFDL's filesystem.

These updates are mostly updates for the Bronx-18 hydrology grid generating tool.

### PR DESCRIPTION
**Pull request by ceblanton**
resolves #13

### CODE REVIEW

**Comment by ceblanton** [comment]
@LuisSalbey I believe this has all the updates

**Comment by rem1776** [comment]
@ceblanton It looks like some of the symlink files that were added in are used to build simple_hydrology so the CI won't be able to build all the tools without [them.](https://github.com/NOAA-GFDL/FRE-NCtools/blob/43427d601517090312675e86e5a626a585b3253e/tools/simple_hydrog/Makefile.am#L4) If we added the files in the test should pass, but I'm guessing they were added in as symlinks to avoid GitHub's 100MB limit?

**Comment by ceblanton** [comment]
@rem1776, Yes, exactly. The input files were too big for github's 100 MB limit, so I symlinked to GFDL's filesystem.

I don't have good a good suggestion on how to get the CI to work properly in terms of building and installing the hydrology script tools. Any ideas, @LuisSalbey ? Can `make install` and `make check` skip the hydrology script if the input files don't exist Eventually, it would be nice to figure out how to store these big files outside GFDL, but having the CI work properly should be good enough for now.

**Comment by LuisSalbey** [comment]
I'll check if the hydrology tool can bypass those big input files...

**Comment by ngs333** [comment]
There are quite a number of compilation problems. Here is what i did to get around them and finish compiling, but these are just workaroung.
1) Remove the unix softlinks and touch (or make) fake files with the same name.
------------------------------------------------------------------------------------
2) This problem appears twice in compilation:

make[2]: Entering directory '/home/mzuniga/fre_big/FRE-NCTools/tools/simple_hydrog/postp'
mpifort -I../../../tools/libfrencutils -fdefault-real-8 -I/usr/include -DINTERNAL_FILE_NML -fcray-pointer -Duse_mpp_io -Waliasing -ffree-line-length-none -fno-range-check -O0 -g -W -fbounds-check  -ffpe-trap=invalid,zero,overflow -I/usr/include  -c -o cp_river_vars.o  cp_river_vars.f90
cp_river_vars.f90:39:50:

   39 | real, dimension (ni_cells,nj_cells)    :: out_flow = &
      |                                                  1
Error: Incompatible ranks 2 and 1 in assignment at (1)
cp_river_vars.f90:309:10:


I moved the inialization from the declaration line and initialized it as the first line pert declarations like this:
out_flow  = reshape((/ 8.,  4.,  2., 16.,  0., 1., 32., 64., 128. /),shape(out_flow))
---------------------------------------------------------------------------------------------
3) This compilation issue with GCC 

Warning: Inequality comparison for REAL(8) at (1) [-Wcompare-reals]
mpicc -DHAVE_CONFIG_H -I. -I../../..    -I/usr/include -I/usr/include/hdf5/serial -I../../../tools/libfrencutils -DINTERNAL_FILE_NML -O0 -g -I/usr/include -I/usr/include/hdf5/serial  -MT affinity.o -MD -MP -MF .deps/affinity.Tpo -c -o affinity.o affinity.c
affinity.c:12:14: error: static declaration of ‘gettid’ follows non-static declaration
   12 | static pid_t gettid(void)
      |              ^~~~~~
In file included from /usr/include/unistd.h:1170,
                 from affinity.c:6:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
   34 | extern __pid_t gettid (void) __THROW;

----------------------------------------------------------------------
 can be resolved like this:
#ifndef __USE_GNU
static pid_t gettid(void)
{
  return syscall(__NR_gettid);
}
#endif

I works but we really need unit tests and more compilers to make sure
--------------------------------------------------------------------------------------------
4) Finally , this compilation issue:
rmv_parallel_rivers.f90:74:17:

   74 | add_ocean_const= "F"
      |                 1
Error: Cannot convert CHARACTER(1) to LOGICAL(4) at (1)
rmv_parallel_rivers.f90:265:10:

can be resolved like this:
add_ocean_const= .false.

**Comment by ceblanton** [comment]
closing this, and re-opening with fixes from @ngs333 (#16)

**Pull request closed without merging**
