### PR TITLE
Improved ax_lib_netcdf.m4

### LINKED ISSUE #19: Issues with simple_hydrog and netCDF-Fortran
**Describe the bug**

There is a GNU make issue with how a couple directories in `simple_hydrog` handle netCDF-Fortran. They assume netCDF-Fortran was built in a specific way. For example I had to change these:

https://github.com/NOAA-GFDL/FRE-NCtools/blob/214e569a5383d75e1dcd5099a36a70dca8700f15/tools/simple_hydrog/rmvpr/Makefile.am#L9

https://github.com/NOAA-GFDL/FRE-NCtools/blob/214e569a5383d75e1dcd5099a36a70dca8700f15/tools/simple_hydrog/postp/Makefile.am#L9

in the final `Makefile` to look like:
```
LDADD = $(NETCDF_LDFLAGS) $(NETCDF_LIBS) $(NETCDF_FCLIBS)
```

In our netCDF we have a looooooot of stuff we built our netCDF-Fortran with:
```
$ /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/bin/nf-config --flibs
-L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lnetcdff -lnetcdf -lm 
-L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lnetcdf -ljpeg -lmfhdf -ldf -ljpeg -lhdf5_hl -lhdf5 -lm 
-L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lmfhdf -ldf -lsz -ljpeg -lgpfs 
-L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lz -lm -ldl -lm 
-L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lz -lm
```
so I think it's best to use `NETCDF_FLIBS` if passed in by the user.

**To Reproduce**

I ran `make` and got:
```
mpiifort -I../../../tools/libfrencutils -real_size 64 -I/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/include/netcdf -g   -o rmv_parallel_rivers rmv_parallel_rivers.o ../../../tools/libfrencutils/libfrencutils.a -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib  -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lnetcdf -ljpeg -lmfhdf -ldf -ljpeg -lhdf5_hl -lhdf5 -lm -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lmfhdf -ldf -lsz -ljpeg -lgpfs -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lz -lm -ldl -lm -lnetcdff -lnetcdf -lhdf5_hl  -lhdf5 -lz -ldl
ld: /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib/libnetcdf.a(hdf4file.o): in function `hdf4_rec_grp_del':
/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:70: undefined reference to `SDendaccess'
ld: /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib/libnetcdf.a(hdf4file.o): in function `hdf4_read_att':
/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:300: undefined reference to `SDattrinfo'
ld: /gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:322: undefined reference to `SDreadattr'
ld: /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib/libnetcdf.a(hdf4file.o): in function `hdf4_read_dim':
/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:359: undefined reference to `SDgetdimid'
ld: /gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:361: undefined reference to `SDdiminfo'
ld: /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib/libnetcdf.a(hdf4file.o): in function `hdf4_read_var':
/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:502: undefined reference to `SDselect'
ld: /gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:506: undefined reference to `SDgetinfo'
ld: /gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:511: undefined reference to `SDgetchunkinfo'
ld: /gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:522: undefined reference to `SDgetfillvalue'
ld: /discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib/libnetcdf.a(hdf4file.o): in function `NC_HDF4_open':
/gpfsm/dswdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/src/netcdf/libhdf4/hdf4file.c:629: undefined reference to `SDstart'
```
and it kept going. It was missing the link to cURL (we build with OpenDAP support), the link to the zip and szlib libraries, etc.

**Expected behavior**
The file should link.

**System Environment**
Describe the system environment, include:
- OS: SLES 12 SP3
- Compiler(s): Intel 19.1.2 IMPI 19.1.2
- netCDF Version: 4.7.4 (C), 4.5.2 (Fortran) 
- Configure options: 
```
  $ ./configure --prefix=/discover/swdev/gmao_SIteam/other/SLES12.3/FRE-NCtools/2020Nov10 --with-netcdf=/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux --with-netcdf-fortran=/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux --with-mpi=yes CC=mpiicc FC=mpiifort NETCDF_LIBS=-L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lnetcdf -ljpeg -lmfhdf -ldf -ljpeg -lhdf5_hl -lhdf5 -lm -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lmfhdf -ldf -lsz -ljpeg -lgpfs -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lz -lm -ldl -lm NETCDF_FCLIBS=-L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lnetcdff -lnetcdf -lm -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lnetcdf -ljpeg -lmfhdf -ldf -ljpeg -lhdf5_hl -lhdf5 -lm -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lmfhdf -ldf -lsz -ljpeg -lgpfs -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lz -lm -ldl -lm -L/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux/lib -lcurl -lssl -lcrypto -lssl -lcrypto -lz -lm
```

This is a bit long, so in other words I do:
```
BASEDIR=/discover/swdev/gmao_SIteam/Baselibs/ESMA-Baselibs-6.0.16/x86_64-unknown-linux-gnu/ifort_19.1.2.254-intelmpi_19.1.2.254/Linux

NETCDF_LIBS=$($BASEDIR/bin/nc-config --libs)
NETCDF_FCLIBS=$($BASEDIR/bin/nf-config --flibs)

PREFIX=/discover/swdev/gmao_SIteam/other/SLES12.3/FRE-NCtools/2020Nov10

./configure --prefix=${PREFIX} --with-netcdf=${BASEDIR} --with-netcdf-fortran=${BASEDIR} \
   --with-mpi=yes CC=${CC} FC=${FC} NETCDF_LIBS="${NETCDF_LIBS}" NETCDF_FCLIBS="${NETCDF_FCLIBS}"
```
where I use the output of `nc-config --libs` and `nf-config --flibs` to tell the `configure` script what `NETCDF_LIBS` and `NETCDF_FCLIBS` will be as we build netCDF with support.

NOTE: Due to a fun bug in netCDF-Fortran 4.5.3, `nf-config --flibs` is broken, so that's why I'm not using the newest version. The fix is in their `main` branch, so hopefully all is well in the next version.

### PR DESCRIPTION
**Pull request by underwoo**
A large refactor of the ax_lib_netcdf.m4 macros.  This update better supports systems that don't have working n[cf]-config applications

More work still needs to be done, as there are large sections that are essentially copy/replace and can be better organized.

Fixes #19

### CODE REVIEW

**Comment by underwoo** [comment]
The check are failing due to `csh` not being available in the Docker image.  Although, if `csh` were available the checks would still fail as the scripts are written for use on the [NOAA RDHPCS PPAN system](https://www.noaa.gov/organization/information-technology/ppan).  #22 _should_ fix that problem.

**Review by ngs333 — APPROVED** [review]

**Comment by ngs333** [comment]
FYI, I also checked that it builds on AMD + Ubuntu Linux.

**Review by laurenchilutti — APPROVED** [review]
I've looked over the code, and just to do a simple test, I installed this on Orion and it worked.  As long as you know why the checks are failing and feel it is ready to merge, it looks good to me.

**Comment by underwoo** [comment]
> I've looked over the code, and just to do a simple test, I installed this on Orion and it worked.  As long as you know why the checks are failing and feel it is ready to merge, it looks good to me.

The tests are failing due to not having `csh` or the sample data for one or more of the tests. There will be issues and PRs to resolve those later.

**Review by mlee03 — APPROVED** [review]
I only tested compilation on Gaea and Skylake where there were no difficulties setting the NetCDF configurations with nc-config, so it wasn't an extensive test.  The comments in the .m4 file are very helpful :D

**Review by ceblanton — APPROVED** [review]

**Pull request merged**
